version: '3'
services:
  magento:
    image: vinhnv95/mftf:2.2.10-apache-php7.1
    command: bash -c "sleep 5; su www-data -s /bin/bash -c 'php bin/magento setup:store-config:set --base-url=http://192.168.130.46:7080/'; /usr/local/bin/run-apache"
    volumes:
      - ./server/app/code/Magestore:/var/www/html/app/code/Magestore
      - ../.htaccess:/var/www/html/.htaccess
      - ./pub/apps:/var/www/html/pub/apps
      - ./server/app/tests/Magestore/PosSampleData:/var/www/html/app/code/Magestore/PosSampleData
      - ./server/app/tests/static/Webpos/phpunit.xml:/var/www/html/dev/tests/static/phpunit.xml
      - ./server/app/tests/static/Webpos/changed_file.txt:/var/www/html/dev/tests/static/testsuite/Magento/Test/_files/changed_file.txt
      - ../old.txt:/var/www/html/dev/tests/static/testsuite/Magento/Test/Less/_files/changed_file.txt
      - ./server/app/tests/static/Webpos/changed_file.txt:/var/www/html/dev/tests/static/testsuite/Magento/Test/Less/_files/blacklist/old.txt
      - ./server/app/tests/static/Webpos/changed_file.txt:/var/www/html/dev/tests/static/testsuite/Magento/Test/Html/_files/changed_file.txt
    ports:
      - 7080:80
    environment:
      BASE_URL: http://192.168.130.46:7080/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  db:
    image: vinhnv95/mftf-db:2.2.10-percona
    environment:
      MYSQL_ROOT_PASSWORD: magento
    volumes:
      - ../db/conf.d:/etc/my.cnf.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7060:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 7020:8025
    networks:
      - webnet

networks:
  webnet:
