version: '3'
services:
  magento:
    image: magestore/mftf:2.3.4-apache-php7.2
    # command: bash -c "sleep 5; su www-data -s /bin/bash -c 'php bin/magento setup:store-config:set --base-url=http://192.168.130.46:7087/'; /usr/local/bin/run-apache"
    volumes:
      # - ./server/app/code/Magestore:/var/www/html/app/code/Magestore
      - ../.htaccess:/var/www/html/.htaccess
      # - ./pub/apps/pos:/var/www/html/pub/apps/pos
      # - ./server/app/tests/Magestore/PosSampleData:/var/www/html/app/code/Magestore/PosSampleData
    ports:
      - 7087:80
    environment:
      BASE_URL: http://192.168.130.46:7087/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  db:
    image: magestore/mftf-db:2.3.4-percona
    environment:
      MYSQL_ROOT_PASSWORD: magento
    volumes:
      - ../db/conf.d:/etc/my.cnf.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7067:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 7027:8025
    networks:
      - webnet

networks:
  webnet:
