version: '3'
services:
  magento:
    image: magestore/mftf:2.4.5-apache-php8.1
    command: bash -c "sleep 5; service cron restart; su www-data -s /bin/bash -c 'php bin/magento cron:install'; /usr/local/bin/run-apache"
    volumes:
      - ./Source/server/app/code/Magestore:/var/www/html/app/code/Magestore
      - ../pub/.htaccess:/var/www/html/pub/.htaccess
      - ./pub/apps:/var/www/html/pub/apps
    ports:
      - 9088:80
    environment:
      BASE_URL: http://127.0.0.1:9088/
      MAGENTO_DEV_MODE: developer
      ELASTICSEARCH_VERSION: elasticsearch7
    networks:
      webnet:
        aliases:
          - localhost.com
  
  elasticsearch:
    image: elasticsearch:7.7.0
    ports:
      - 9038:9200
    environment:
      - discovery.type=single-node
    networks:
      - webnet

  db:
    image: magestore/mftf-db:2.4.5-percona
    environment:
      MYSQL_ROOT_PASSWORD: magento
    volumes:
      - ../db/conf.d:/etc/my.cnf.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9068:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 9028:8025
    networks:
      - webnet

networks:
  webnet:
