version: '3'
services:
  magento:
    image: 192.168.130.18:5000/mftf:ee-2.3.3-apache-php7.2
    volumes:
      - ./server/app/code/Magestore:/var/www/html/app/code/Magestore
      - ../.htaccess:/var/www/html/.htaccess
      - ./pub/apps:/var/www/html/pub/apps
      # - ./server/app/tests/Magestore/PosSampleData:/var/www/html/app/code/Magestore/PosSampleData
    ports:
      - 7090:80
    environment:
      BASE_URL: http://192.168.130.46:7090/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  db:
    image: 192.168.130.18:5000/mftf-db:ee-2.3.3-percona
    environment:
      MYSQL_ROOT_PASSWORD: magento
    volumes:
      - ../db/conf.d:/etc/my.cnf.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7070:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 7030:8025
    networks:
      - webnet

networks:
  webnet:
